src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?CategorieArticle $categorieArticle = null;

    /**
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'article')]
    private Collection $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCategorieArticle(): ?CategorieArticle
    {
        return $this->categorieArticle;
    }

    public function setCategorieArticle(?CategorieArticle $categorieArticle): static
    {
        $this->categorieArticle = $categorieArticle;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }

    function extraitSansCouperMot() {
        if (strlen($this->description) <= 255) {
            return $this->description;
        }
    
        $extrait = substr($this->description, 0, 255);
    
        $espacePos = strrpos($extrait, ' ');
    
        if ($espacePos !== false) {
            $extrait = substr($extrait, 0, $espacePos);
        }
        $extrait = $extrait . "...";
        return $extrait;
    }

    public function __toString(): string
    {
        return $this->id;
    }
}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private ?bool $statut = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article = null;

    #[ORM\ManyToOne(inversedBy: 'Commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): static
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $date): static
    {
        $this->dateCreation = $date;

        return $this;
    }

    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(?bool $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): static
    {
        $this->article = $article;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\CategorieArticle;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description', TextareaType::class, [
                'required' => false, // Juste pour tester
            ])
            ->add('date_creation', null, [
                'widget' => 'single_text',
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
            ->add('categorieArticle', EntityType::class, [
                'class' => CategorieArticle::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\User;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\SecurityBundle\Security;

#[Route('/article')]
final class ArticleController extends AbstractController
{
    #[Route(name: 'app_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        $articles = $articleRepository->findAll();
        foreach ($articles as $article) {
            $article->setDescription($article->extraitSansCouperMot());
        }
        // dd($article);
        return $this->render('article/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article, CommentaireRepository $commentaireRepository, Security $security): Response
    {
        $user = $security->getUser();
        if($user->getRoles() == "ROLE_ADMIN"){
            $comments = $commentaireRepository->findAll();
        }else{
            $comments = $commentaireRepository->findByIdArticle($article->getId());
        }

        return $this->render('article/show.html.twig', [
            'article' => $article,
            'coms' => $comments,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block main %}
    <h1 class="mb-4">Blog :</h1>
    {% if is_granted("ROLE_ADMIN") or  is_granted("ROLE_REDACTEUR") %}
        <a class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded shadow-lg" href="{{ path('app_article_new') }}">Ajouter un article</a>
    {% endif %}
    <div class=" grid grid-cols-3 gap-1">
        {% for article in articles %}
            <div class="mt-2">
                <div class="max-w-lg rounded overflow-hidden shadow-lg">
                    <div class="px-6 py-4">
                        <div class="font-bold text-xl mb-2">{{ article.titre }}</div>
                        <div class="text-gray-700 text-base">
                            {{ article.description|raw }}
                        </div>
                    </div>
                    <div class="px-6 pt-4 pb-2">
                        <div class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                            <span>Écrit par : {{ article.user }} </span>
                            <span> Publié le : {{ article.dateCreation ? article.dateCreation|date('Y-m-d H:i:s') : '' }} </span>
                        </div>
                        <div class="mt-2 mb-2">
                            {# <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_commentaire_new', {'id': article.id}) }}">Ajouter un commentaire</a> #}
                            <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_article_show', {'id': article.id}) }}">Voir l'article</a>
                        </div>
                    </div>
                </div>
            </div>
            {# <div>
                {% for com in article.commentaires %}
                <div class="max-w-lg rounded overflow-hidden shadow-lg">
                    <div class="px-6 py-4">
                        <p>{{ com.user }} {{ com.dateCreation ? com.dateCreation|date('Y-m-d H:i:s') : '' }}</p>
                        <div class="text-gray-700 text-base">
                            {{ com.contenu|raw }}
                        </div>
                    </div>
                    <div class="px-6 pb-2">
                        <div class="mt-2 mb-2">
                            <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_commentaire_new', {'id': article.id}) }}">Repondre</a>
                        </div>
                    </div>
                </div>
                {% else %}
                    <p>pas de commentaire pour cet article</p>
                {% endfor %}
            </div> #}
        {% else %}
            <p colspan="5">no records found</p>
        {% endfor %}
    </div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block main %}
    <h1>Create new Article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('app_article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block main %}
    <div class=" rounded overflow-hidden shadow-lg">
        <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">{{ article.titre }}</div>
            <div class="text-gray-700 text-base">
                {{ article.description|raw }}
            </div>
        </div>
        <div class="px-6 pt-4 pb-2">
            <div class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                <span>Écrit par : {{ article.user }} </span>
                <span> Publié le : {{ article.dateCreation ? article.dateCreation|date('Y-m-d H:i:s') : '' }} </span>
            </div>
            <div class="mt-2 mb-2">
                {# <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_commentaire_new', {'id': article.id}) }}">Ajouter un commentaire</a> #}
                <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_commentaire_new', {'id': article.id}) }}">Ajouter un commentaire</a>
            </div>
        </div>
    </div>
    <h3 class="text-xl">Commentaire :</h3>
    <div>
        {% if is_granted("ROLE_ADMIN") %}
            {% for com in article.commentaires %}
                <div class="rounded overflow-hidden">
                    <div class="px-6 py-4">
                        <div class="flex items-center">
                            <img src="{{ asset('image/avatar.png') }}" alt="logo" width="50px">
                            <p>{{ com.user }} {{ com.dateCreation ? com.dateCreation|date('Y-m-d H:i:s') : '' }}</p>
                            <p class="inline-block bg-gray-200 rounded-full px-3 py-1 text-xs font-semibold text-gray-700 mr-2 ml-2">{{ com.user.roles[0] }}<p>
                        </div>
                        <div class="text-gray-700 text-base ml-12.5">
                            <p>{{ com.contenu|raw }}<p>
                            <div class="flex mt-2">
                                <i class="fa-solid fa-thumbs-up pr-4"></i>
                                <i class="fa-solid fa-thumbs-down"></i>
                            </div>
                        </div>
                    </div>
                    {% if com.statut == false %}
                    <div class="px-6">
                        <p>Ce commentaire n'a pas encore était validé.</p>
                        {# <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_commentaire_new', {'id': article.id}) }}">Repondre</a> #}
                    </div>
                    {% endif %}
                </div>
            {% else %}
                <p>pas de commentaire pour cet article</p>
            {% endfor %}
        {% else %}
            {% for com in coms %}
                <div class="rounded overflow-hidden">
                    <div class="px-6 py-4">
                        <div class="flex items-center">
                            <img src="{{ asset('image/avatar.png') }}" alt="logo" width="50px">
                            <p>{{ com.user }} {{ com.dateCreation ? com.dateCreation|date('Y-m-d H:i:s') : '' }}</p>
                            <p class="inline-block bg-gray-200 rounded-full px-3 py-1 text-xs font-semibold text-gray-700 mr-2 ml-2">{{ com.user.roles[0] }}<p>
                        </div>
                        <div class="text-gray-700 text-base">
                            {{ com.contenu|raw }}
                        </div>
                        <div class="flex mt-2">
                            <i class="fa-solid fa-thumbs-up pr-4"></i>
                            <i class="fa-solid fa-thumbs-down"></i>
                        </div>
                    </div>
                    {% if com.statut == false %}
                    <div class="px-6">
                        <p>Votre commentaire a été désactivé. Vous êtes seul à le voir</p>
                        {# <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_commentaire_new', {'id': article.id}) }}">Repondre</a> #}
                    </div>
                    {% endif %}
                </div>
            {% else %}
                <p>pas de commentaire pour cet article</p>
            {% endfor %}
        {% endif %}
    </div>

    <a class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" href="{{ path('app_article_index') }}">Retour</a>

    {# {{ include('article/_delete_form.html.twig') }} #}
{% endblock %}